version: '3.8'

services:
  football-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/app/data/football.db
      - JWT_SECRET=your-production-jwt-secret-change-this
      - JWT_REFRESH_SECRET=your-production-refresh-secret-change-this
      - UPLOAD_PATH=/app/uploads
      - MAX_FILE_SIZE=5242880
      - FRONTEND_URL=http://localhost:3001
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_AUTH_MAX_REQUESTS=5
      - LOG_LEVEL=info
      - LOG_FILE=/app/logs/app.log
    volumes:
      - football_data:/app/data
      - football_logs:/app/logs
      - football_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - football-api
  #   restart: unless-stopped

volumes:
  football_data:
    driver: local
  football_logs:
    driver: local
  football_uploads:
    driver: local

networks:
  default:
    name: football-network 